#!/usr/bin/env bash
: "${K8S_CONF_COLLECTION:=${HOME}/.kube/configs}"

CONFIGS=()
for filename in ${K8S_CONF_COLLECTION}/*; do
    CONFIGS+=($filename)
done
KUBECONFIG=$(join_by ', ' $CONFIGS)
function join_by { local IFS="$1"; shift; echo "$*"; }
