#!/usr/bin/env bash

function join_by { local IFS="$1"; shift; echo "$*"; }

: "${K8S_CONF_COLLECTION:=${HOME}/.kube/configs}"

CONFIGS=()
for filename in ${K8S_CONF_COLLECTION}/*; do
    CONFIGS+=($filename)
done
export KUBECONFIG=$(join_by ', ' $CONFIGS)
